### ISSUE TITLE
Where is extract_embeddings?

### ISSUE THREAD

**Issue by CBrenz-cmd** [AshishBhatnagar022/FaceRecognition#1]
Hello, thank you for your work.

I noticed that in the source code one of the imports is the load_model() function from extract_embeddings, even though there is no extract_embeddings.py file. Is it missing or am I mistaken?

Cheers and thanks!

**Comment by AshishBhatnagar022** [comment]
Yeah. It was my mistake .Now I have uploaded the required file.

**Comment by CBrenz-cmd** [comment]
Hello, thank you for uploading the file.

May I also ask if you know how to resolve this error? Is the weights h5 file missing?

Unable to open file (unable to open file: name = 'weights/vgg_face_weights.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Thank you!

**Comment by benExact** [comment]
@CBrenz-cmd Did you manage to resolve your second issue about the weights h5 file missing?

I am facing the same issue at the moment.
